### ISSUE TITLE
Method names are confusing

### ISSUE THREAD

**Issue by kpiraro** [learn-co-curriculum/ruby-instance-variables#10]
I was pretty confused by the "name=" and "name" methods. It took some experimenting in irb to realize that the equal sign in "name=" is a key mechanism, especially since the other method is also called "name". I clarified it for myself by calling the set method "setName=", which makes it clearer what's going on when you then call "lassie.setName = "Lassie"" and "puts lassie.name"

**Comment by gj** [comment]
Hi @kpiraro !

Out in the wild, you're free to name your methods whatever you like, but the `#attribute` (reader / getter) and `#attribute=` (writer / setter) way of naming methods is a Ruby convention. The lesson goes over the difference in the **[We need instance variables](https://github.com/learn-co-curriculum/ruby-instance-variables#we-need-instance-variables)** section. If you follow that convention, other Rubyists will be able to understand your code better. Also, for what it's worth, all Ruby method names should be _snake_cased_, so `#set_name` instead of `#setName`.

Hope that helps! 💙
